#!/bin/bash

fusermount -u ~/roms/amiga
fusermount -u ~/roms/amstradcpc
fusermount -u ~/roms/arcade
fusermount -u ~/roms/atari2600
fusermount -u ~/roms/atari5200
fusermount -u ~/roms/atari7800
fusermount -u ~/roms/atari800
fusermount -u ~/roms/atarijaguar
fusermount -u ~/roms/atarilynx
fusermount -u ~/roms/atarist
fusermount -u ~/roms/c64
fusermount -u ~/roms/mame
fusermount -u ~/roms/ps1
fusermount -u ~/roms/ps2
fusermount -u ~/roms/psp
fusermount -u ~/roms/sega1000
fusermount -u ~/roms/sega32x
fusermount -u ~/roms/segacd
fusermount -u ~/roms/segadc
fusermount -u ~/roms/segagg
fusermount -u ~/roms/segamd
fusermount -u ~/roms/segams
fusermount -u ~/roms/segasaturn
fusermount -u ~/roms/dos
fusermount -u ~/roms/gamecube
fusermount -u ~/roms/n64
fusermount -u ~/roms/snes
fusermount -u ~/roms/nes
