name: Gamelists updater

on:
  workflow_dispatch:
  schedule:
    # Every Sunday at 04:00 UTC
    - cron: '0 4 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: bash gamelist.sh
