name: Run Script Periodically

on:
  push:  # Spustí sa pri každom pushnutí (teda aj pri commite)
    branches:
      - main  # Môžeš zmeniť na inú vetvu
  workflow_dispatch:  # Umožní manuálne spustenie

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Stiahne kód repozitára

      - name: Run script
        run: bash lowresnx.sh  # Spustí tvoj skript
